#!/bin/bash

sed -i 's/MIMI_BsV/IM_16@MIMI_BsV/' $1
sed -i 's/MIMI_ChoanoV-1/IM_08@MIMI_ChoanoV-1/' $1
sed -i 's/ARCH_Thermococci_archaeon/ARCH@_Thermococci_archaeon/' $1
sed -i 's/ARCH_Halorussus_rarus/ARCH@_Halorussus_rarus/' $1
sed -i 's/ARCH_Candidatus_Woesearchaeota_archaeon/ARCH@_Candidatus_Woesearchaeota_archaeon/' $1
sed -i 's/ARCH_Nitrosopumilales_archaeon/ARCH@_Nitrosopumilales_archaeon/' $1
sed -i 's/ARCH_Euryarchaeota_archaeon/ARCH@_Euryarchaeota_archaeon/' $1
sed -i 's/ARCH_Thermococcus_kodakarensis_KOD1/ARCH@_Thermococcus_kodakarensis_KOD1/' $1
sed -i 's/ARCH_Euryarchaeota_Thermococcus_gorgonarius/ARCH@_Euryarchaeota_Thermococcus_gorgonarius/' $1
sed -i 's/ARCH_Euryarchaeota_Pyrococcus_woesei/ARCH@_Euryarchaeota_Pyrococcus_woesei/' $1
sed -i 's/ARCH_Euryarchaeota_Methanococcus_maripaludis/ARCH@_Euryarchaeota_Methanococcus_maripaludis/' $1
sed -i 's/ARCH_Euryarchaeota_Methanopyrus_kandleri/ARCH@_Euryarchaeota_Methanopyrus_kandleri/' $1
sed -i 's/ARCH_Crenarchaeota_Aeropyrum_pernix_2/ARCH@_Crenarchaeota_Aeropyrum_pernix_2/' $1
sed -i 's/ARCH_Crenarchaeota_Pyrobaculum_aerophilum_2/ARCH@_Crenarchaeota_Pyrobaculum_aerophilum_2/' $1
sed -i 's/ARCH_Euryarchaeota_Archaeoglobus_fulgidus/ARCH@_Euryarchaeota_Archaeoglobus_fulgidus/' $1
sed -i 's/MIMI_PGV/IM_01@MIMI_PGV/' $1
sed -i 's/MIMI_Haptolina_ericina_RF02/IM_01@MIMI_Haptolina_ericina_RF02/' $1
sed -i 's/MIMI_Prymnesium_kappa_virus_RF02/IM_01@MIMI_Prymnesium_kappa_virus_RF02/' $1
sed -i 's/MIMI_OLPV1/IM_01@MIMI_OLPV1/' $1
sed -i 's/MIMI_OLPV2/IM_01@MIMI_OLPV2/' $1
sed -i 's/MIMI_CEV/IM_01@MIMI_CEV/' $1
sed -i 's/MIMI_POV/IM_12@MIMI_POV/' $1
sed -i 's/MIMI_Prymnesium_kappa_virus_RF01/IM_09@MIMI_Prymnesium_kappa_virus_RF01/' $1
sed -i 's/MIMI_TetV-1/IM_12@_MIMI_TetV-1/' $1
sed -i 's/MIMI_AaV/IM_09@_MIMI_AaV/' $1
sed -i 's/MIMI_megavirus_chiliensis/IM_16@_megavirus_chiliensis/' $1
sed -i 's/MIMI_megavirus_lba/IM_16@MIMI_megavirus_lba/' $1
sed -i 's/MIMI_megavirus_courdo7/IM_16@MIMI_megavirus_courdo7/' $1
sed -i 's/MIMI_megavirus_bus/IM_16@MIMI_megavirus_bus/' $1
sed -i 's/MIMI_moumouvirus_ochan/IM_16@MIMI_moumouvirus_ochan/' $1
sed -i 's/MIMI_moumouvirus_monve/IM_16@MIMI_moumouvirus_monve/' $1
sed -i 's/MIMI_moumouvirus_M10A/IM_16@MIMI_moumouvirus_M10A/' $1
sed -i 's/MIMI_terra2/IM_16@MIMI_terra2/' $1
sed -i 's/MIMI_apmv/IM_16@MIMI_apmv/' $1
sed -i 's/MIMI_hirudovirus_Sangsue/IM_16@MIMI_hirudovirus_Sangsue/' $1
sed -i 's/MIMI_pointerouge1/IM_16@MIMI_pointerouge1/' $1
sed -i 's/MIMI_Tupanvirus_soda_lake/IM_16@MIMI_Tupanvirus_soda_lake/' $1
sed -i 's/MIMI_Tupanvirus_deep_ocean/IM_16@MIMI_Tupanvirus_deep_ocean/' $1
sed -i 's/MIMI_Klosneuvirus_KNV1_1/IM_16@MIMI_Klosneuvirus_KNV1_1/' $1
sed -i 's/MIMI_CROV/IM_16@MIMI_CROV/' $1
sed -i 's/MIMI_Namao_virus/IM_16@MIMI_Namao_virus/' $1
sed -i 's/PHYCO_Acanthocystis_turfacea_Chlorella_virus_1/AG_02@PHYCO_Acanthocystis_turfacea_Chlorella_virus_1/' $1
sed -i 's/PHYCO_Paramecium_bursaria_Chlorella_virus_FR483/AG_02@PHYCO_Paramecium_bursaria_Chlorella_virus_FR483/' $1
sed -i 's/PHYCO_Paramecium_bursaria_Chlorella_virus_1/AG_02@PHYCO_Paramecium_bursaria_Chlorella_virus_1/' $1
sed -i 's/PHYCO_Bathycoccus_sp__RCC1105_virus_BpV1/AG_01@PHYCO_Bathycoccus_sp__RCC1105_virus_BpV1/' $1
sed -i 's/PHYCO_Micromonas_sp__RCC1109_virus_MpV1/AG_01@PHYCO_Micromonas_sp__RCC1109_virus_MpV1/' $1
sed -i 's/PHYCO_Ostreococcus_lucimarinus_virus_1/AG_01@PHYCO_Ostreococcus_lucimarinus_virus_1/' $1
sed -i 's/PHYCO_Ostreococcus_tauri_virus_1/AG_01@PHYCO_Ostreococcus_tauri_virus_1/' $1
sed -i 's/PHYCO_Ostreococcus_tauri_virus_2/AG_01@PHYCO_Ostreococcus_tauri_virus_2/' $1
sed -i 's/PHYCO_Micromonas_pusilla_virus_12T/AG_01@PHYCO_Micromonas_pusilla_virus_12T/' $1
sed -i 's/PHYCO_Heterosigma_akashiwo_virus_01/AG_04@PHYCO_Heterosigma_akashiwo_virus_01/' $1
sed -i 's/PHYCO_Emiliania_huxleyi_virus_86/PV_05@PHYCO_Emiliania_huxleyi_virus_86/' $1
sed -i 's/EUKA_Parabasalia_Trichomonas_vaginalis/EUKA@_Parabasalia_Trichomonas_vaginalis/' $1
sed -i 's/EUKA_Amoebozoa_Entamoeba_histolytica_3/EUKA@_Amoebozoa_Entamoeba_histolytica_3/' $1
sed -i 's/EUKA_Amoebozoa_Dictyostelium_discoideum_delta/EUKA@_Amoebozoa_Dictyostelium_discoideum_delta/' $1
sed -i 's/EUKA_Metazoa_Homo_sapiens_delta/EUKA@_Metazoa_Homo_sapiens_delta/' $1
sed -i 's/EUKA_Euglenozoa_Leishmania_major/EUKA@_Euglenozoa_Leishmania_major/' $1
sed -i 's/EUKA_Euglenozoa_Trypanosoma_brucei_3/EUKA@_Euglenozoa_Trypanosoma_brucei_3/' $1
sed -i 's/EUKA_Alveolata_Tetrahymena_thermophila_2/EUKA@_Alveolata_Tetrahymena_thermophila_2/' $1
sed -i 's/EUKA_Fungi_Encephalitozoon_cuniculi/EUKA@_Fungi_Encephalitozoon_cuniculi/' $1
sed -i 's/EUKA_Diplomonadida_Giardia_intestinalis/EUKA@_Diplomonadida_Giardia_intestinalis/' $1
sed -i 's/MED_Medusavirus_Unagene_392/Medusa@MED_Medusavirus_Unagene_392/' $1
sed -i 's/ARCH_Euryarchaeota_Methanosaeta_thermophila/ARCH@_Euryarchaeota_Methanosaeta_thermophila/' $1
sed -i 's/ARCH_Euryarchaeota_Methanosarcina_acetivorans/ARCH@_Euryarchaeota_Methanosarcina_acetivorans/' $1
sed -i 's/MIMI_Klosneuvirus_KNV1_2/IM_16@MIMI_Klosneuvirus_KNV1_2/' $1
sed -i 's/PHYCO_Ectocarpus_siliculosus_virus_1/sedis@_PHYCO_Ectocarpus_siliculosus_virus_1/' $1
sed -i 's/PHYCO_Feldmannia_species_virus/sedis@PHYCO_Feldmannia_species_virus/' $1
sed -i 's/PHYCO_Pandoravirus_dulcis/PV_04@PHYCO_Pandoravirus_dulcis/' $1
sed -i 's/PHYCO_Pandoravirus_salinus/PV_04@PHYCO_Pandoravirus_salinus/' $1
sed -i 's/HERP_Anatid_herpesvirus_1/HERP@_Anatid_herpesvirus_1/' $1
sed -i 's/HERP_Gallid_herpesvirus_2/HERP@_Gallid_herpesvirus_2/' $1
sed -i 's/HERP_Meleagrid_herpesvirus_1/HERP@_Meleagrid_herpesvirus_1/' $1
sed -i 's/HERP_Bovine_herpesvirus_5/HERP@_Bovine_herpesvirus_5/' $1
sed -i 's/HERP_Suid_herpesvirus_1/HERP@_Suid_herpesvirus_1/' $1
sed -i 's/HERP_Equid_herpesvirus_4/HERP@_Equid_herpesvirus_4/' $1
sed -i 's/HERP_Felid_herpesvirus_1/HERP@_Felid_herpesvirus_1/' $1
sed -i 's/HERP_Cercopithecine_herpesvirus_9/HERP@_Cercopithecine_herpesvirus_9/' $1
sed -i 's/HERP_Human_herpesvirus_3/HERP@_Human_herpesvirus_3/' $1
sed -i 's/HERP_Macacine_herpesvirus_1/HERP@_Macacine_herpesvirus_1/' $1
sed -i 's/HERP_Psittacid_herpesvirus_1/HERP@_Psittacid_herpesvirus_1/' $1
sed -i 's/HERP_Bovine_herpesvirus_4/HERP@_Bovine_herpesvirus_4/' $1
sed -i 's/HERP_Saimiriine_herpesvirus_2/HERP@_Saimiriine_herpesvirus_2/' $1
sed -i 's/HERP_Human_herpesvirus_8/HERP@_Human_herpesvirus_8/' $1
sed -i 's/HERP_Macacine_herpesvirus_5/HERP@_Macacine_herpesvirus_5/' $1
sed -i 's/HERP_Equid_herpesvirus_2/HERP@_Equid_herpesvirus_2/' $1
sed -i 's/HERP_Murid_herpesvirus_4/HERP@_Murid_herpesvirus_4/' $1
sed -i 's/HERP_Alcelaphine_herpesvirus_1/HERP@_Alcelaphine_herpesvirus_1/' $1
sed -i 's/HERP_Human_herpesvirus_4_type_2/HERP@_Human_herpesvirus_4_type_2/' $1
sed -i 's/HERP_Callitrichine_herpesvirus_3/HERP@_Callitrichine_herpesvirus_3/' $1
sed -i 's/HERP_Panine_herpesvirus_2/HERP@_Panine_herpesvirus_2/' $1
sed -i 's/HERP_Human_herpesvirus_5/HERP@_Human_herpesvirus_5/' $1
sed -i 's/HERP_Macacine_herpesvirus_3/HERP@_Macacine_herpesvirus_3/' $1
sed -i 's/HERP_Tupaiid_herpesvirus_1/HERP@_Tupaiid_herpesvirus_1/' $1
sed -i 's/HERP_Murid_herpesvirus_2/HERP@_Murid_herpesvirus_2/' $1
sed -i 's/HERP_Human_herpesvirus_6A/HERP@_Human_herpesvirus_6A/' $1
sed -i 's/HERP_Human_herpesvirus_7/HERP@_Human_herpesvirus_7/' $1
sed -i 's/MRS_lausannevirus/PM_05@MRS_lausannevirus/' $1
sed -i 's/MRS_T19/PM_05@MRS_T19/' $1
sed -i 's/ASCO_Heliothis_virescens_ascovirus_3e/PM_02@ASCO_Heliothis_virescens_ascovirus_3e/' $1
sed -i 's/ASCO_Spodoptera_frugiperda_ascovirus_1a/PM_02@ASCO_Spodoptera_frugiperda_ascovirus_1a/' $1
sed -i 's/ASCO_Trichoplusia_ni_ascovirus_2c/PM_02@ASCO_Trichoplusia_ni_ascovirus_2c/' $1
sed -i 's/IRID_Infectious_spleen_and_kidney_necrosis_virus/PM_03@IRID_Infectious_spleen_and_kidney_necrosis_virus/' $1
sed -i 's/IRID_Lymphocystis_disease_virus_-_isolate_China/PM_03@IRID_Lymphocystis_disease_virus_-_isolate_China/' $1
sed -i 's/IRID_Lymphocystis_disease_virus_1/PM_03@IRID_Lymphocystis_disease_virus_1/' $1
sed -i 's/IRID_Singapore_grouper_iridovirus/PM_03@IRID_Singapore_grouper_iridovirus/' $1
sed -i 's/IRID_Invertebrate_iridescent_virus_3/PM_02@IRID_Invertebrate_iridescent_virus_3/' $1
sed -i 's/IRID_Invertebrate_iridescent_virus_6/PM_02@IRID_Invertebrate_iridescent_virus_6/' $1
sed -i 's/PITH_pithovirus/PM_07@PITH_pithovirus/' $1
sed -i 's/BACT_Proteobacteria_Aeromonas_hydrophila/BACT@_Proteobacteria_Aeromonas_hydrophila/' $1
sed -i 's/BACT_Proteobacteria_Shigella_boydii/BACT@_Proteobacteria_Shigella_boydii/' $1
sed -i 's/BACT_Proteobacteria_Shewanella_frigidimarina/BACT@_Proteobacteria_Shewanella_frigidimarina/' $1
sed -i 's/ARCH_Euryarchaeota_Methanocella_arvoryzae_2/ARCH@_Euryarchaeota_Methanocella_arvoryzae_2/' $1
sed -i 's/ARCH_Euryarchaeota_uncultured_euryarchaeote/ARCH@_Euryarchaeota_uncultured_euryarchaeote/' $1
sed -i 's/ARCH_Euryarchaeota_Thermoplasma_acidophilum/ARCH@_Euryarchaeota_Thermoplasma_acidophilum/' $1
sed -i 's/ARCH_Crenarchaeota_Sulfolobus_solfataricus/ARCH@_Crenarchaeota_Sulfolobus_solfataricus/' $1
sed -i 's/ARCH_Crenarchaeota_Pyrobaculum_aerophilum/ARCH@_Crenarchaeota_Pyrobaculum_aerophilum/' $1
sed -i 's/ARCH_Crenarchaeota_Aeropyrum_pernix/ARCH@_Crenarchaeota_Aeropyrum_pernix/' $1
sed -i 's/ARCH_Thaumarchaeota_Cenarchaeum_symbiosum/ARCH@_Thaumarchaeota_Cenarchaeum_symbiosum/' $1
sed -i 's/PHAG_ARCH_Halorubrum_phage_HF2/PHAG@_ARCH_Halorubrum_phage_HF2/' $1
sed -i 's/ARCH_Euryarchaeota_Methanospirillum_hungatei/ARCH@_Euryarchaeota_Methanospirillum_hungatei/' $1
sed -i 's/ARCH_Euryarchaeota_Haloarcula_marismortui/ARCH@_Euryarchaeota_Haloarcula_marismortui/' $1
sed -i 's/ARCH_Euryarchaeota_Halobacterium_salinarum/ARCH@_Euryarchaeota_Halobacterium_salinarum/' $1
sed -i 's/EUKA_Rhodophyta_Cyanidioschyzon_merolae_zeta/EUKA@_Rhodophyta_Cyanidioschyzon_merolae_zeta/' $1
sed -i 's/EUKA_Metazoa_Homo_sapiens_zeta/EUKA@_Metazoa_Homo_sapiens_zeta/' $1
sed -i 's/EUKA_Euglenozoa_Leishmania_major_2/EUKA@_Euglenozoa_Leishmania_major_2/' $1
sed -i 's/EUKA_Euglenozoa_Trypanosoma_brucei_2/EUKA@_Euglenozoa_Trypanosoma_brucei_2/' $1
sed -i 's/EUKA_Parabasalia_Trichomonas_vaginalis_3/EUKA@_Parabasalia_Trichomonas_vaginalis_3/' $1
sed -i 's/EUKA_Amoebozoa_Dictyostelium_discoideum/EUKA@_Amoebozoa_Dictyostelium_discoideum/' $1
sed -i 's/EUKA_Amoebozoa_Entamoeba_histolytica_2/EUKA@_Amoebozoa_Entamoeba_histolytica_2/' $1
sed -i 's/VIR_Glossinavirus/VIR@_Glossinavirus/' $1
sed -i 's/VIR_Muscavirus/VIR@_Muscavirus/' $1
sed -i 's/EUKA_Alveolata_Tetrahymena_thermophila/EUKA@_Alveolata_Tetrahymena_thermophila/' $1
sed -i 's/EUKA_Alveolata_Tetrahymena_thermophila_3/EUKA@_Alveolata_Tetrahymena_thermophila_3/' $1
sed -i 's/EUKA_Alveolata_Plasmodium_falciparum_2/EUKA@_Alveolata_Plasmodium_falciparum_2/' $1
sed -i 's/EUKA_Alveolata_Plasmodium_falciparum/EUKA@_Alveolata_Plasmodium_falciparum/' $1
sed -i 's/PHAG_Aeromonas_phage_Aeh1/PHAG@_Aeromonas_phage_Aeh1/' $1
sed -i 's/PHAG_Aeromonas_phage_phiAS5/PHAG@_Aeromonas_phage_phiAS5/' $1
sed -i 's/PHAG_Vibrio_phage_KVP40/PHAG@_Vibrio_phage_KVP40/' $1
sed -i 's/PHAG_Enterobacteria_phage_JS98/PHAG@_Enterobacteria_phage_JS98/' $1
sed -i 's/PHAG_Enterobacteria_phage_RB69/PHAG@_Enterobacteria_phage_RB69/' $1
sed -i 's/PHAG_Shigella_phage_SP18/PHAG@_Shigella_phage_SP18/' $1
sed -i 's/PHAG_Enterobacteria_phage_T4/PHAG@_Enterobacteria_phage_T4/' $1
sed -i 's/PHAG_Enterobacteria_phage_RB16/PHAG@_Enterobacteria_phage_RB16/' $1
sed -i 's/PHAG_Klebsiella_phage_KP15/PHAG@_Klebsiella_phage_KP15/' $1
sed -i 's/PHAG_Enterobacteria_phage_RB49/PHAG@_Enterobacteria_phage_RB49/' $1
sed -i 's/PHAG_Prochlorococcus_phage_P-SSM2/PHAG@_Prochlorococcus_phage_P-SSM2/' $1
sed -i 's/PHAG_Prochlorococcus_phage_P-SSM4/PHAG@_Prochlorococcus_phage_P-SSM4/' $1
sed -i 's/PHAG_Synechococcus_phage_syn9/PHAG@_Synechococcus_phage_syn9/' $1
sed -i 's/PHAG_Synechococcus_phage_S-PM2/PHAG@_Synechococcus_phage_S-PM2/' $1
sed -i 's/PHAG_Synechococcus_phage_S-RSM4/PHAG@_Synechococcus_phage_S-RSM4/' $1
sed -i 's/PHAG_Shigella_phage_Ag3/PHAG@_Shigella_phage_Ag3/' $1
sed -i 's/PHAG_Deftia_phage_phiW-14/PHAG@_Deftia_phage_phiW-14/' $1
sed -i 's/EUKA_Rhodophyta_Cyanidioschyzon_merolae_alpha/EUKA@_Rhodophyta_Cyanidioschyzon_merolae_alpha/' $1
sed -i 's/EUKA_Metazoa_Homo_sapiens/EUKA@_Metazoa_Homo_sapiens/' $1
sed -i 's/EUKA_Alveolata_Cryptosporidium_parvum/EUKA@_Alveolata_Cryptosporidium_parvum/' $1
sed -i 's/EUKA_Amoebozoa_Dictyostelium_discoideum_alpha/EUKA@_Amoebozoa_Dictyostelium_discoideum_alpha/' $1
sed -i 's/EUKA_Euglenozoa_Trypanosoma_brucei/EUKA@_Euglenozoa_Trypanosoma_brucei/' $1
sed -i 's/EUKA_Fungi_Encephalitozoon_cuniculi_2/EUKA@_Fungi_Encephalitozoon_cuniculi_2/' $1
sed -i 's/EUKA_Amoebozoa_Entamoeba_histolytica/EUKA@_Amoebozoa_Entamoeba_histolytica/' $1
sed -i 's/EUKA_Alveolata_Tetrahymena_thermophila_4/EUKA@_Alveolata_Tetrahymena_thermophila_4/' $1
sed -i 's/EUKA_Alveolata_Theileria_parva/EUKA@_Alveolata_Theileria_parva/' $1
sed -i 's/EUKA_Parabasalia_Trichomonas_vaginalis_2/EUKA@_Parabasalia_Trichomonas_vaginalis_2/' $1
sed -i 's/ARCH_Euryarchaeota_Methanocella_arvoryzae/ARCH@_Euryarchaeota_Methanocella_arvoryzae/' $1
sed -i 's/POX_Amsacta_moorei_entomopoxvirus__L_/PX_01@POX_Amsacta_moorei_entomopoxvirus__L_/' $1
sed -i 's/POX_Melanoplus_sanguinipes_entomopoxvirus/PX_01@POX_Melanoplus_sanguinipes_entomopoxvirus/' $1
sed -i 's/POX_Deerpox_virus_W-1170-84/PX_01@POX_Deerpox_virus_W-1170-84/' $1
sed -i 's/POX_Yaba-like_disease_virus/PX_01@POX_Yaba-like_disease_virus/' $1
sed -i 's/POX_Monkeypox_virus_Zaire-96-I-16/PX_01@POX_Monkeypox_virus_Zaire-96-I-16/' $1
sed -i 's/POX_Molluscum_contagiosum_virus_subtype_1/PX_01@POX_Molluscum_contagiosum_virus_subtype_1/' $1
sed -i 's/POX_Orf_virus/PX_01@POX_Orf_virus/' $1
sed -i 's/POX_Fowlpox_virus/PX_01@POX_Fowlpox_virus/' $1
sed -i 's/POX_Nile_crocodilepox_virus/PX_01@POX_Nile_crocodilepox_virus/' $1
sed -i 's/ARCH_Crenarchaeota_Pyrobaculum_calidifontis/ARCH@_Crenarchaeota_Pyrobaculum_calidifontis/' $1
sed -i 's/ASFV_African_swine_fever_virus/AF_01@ASFV_African_swine_fever_virus/' $1
sed -i 's/ASFV_Pacmanvirus_A23/AF_01@ASFV_Pacmanvirus_A23/' $1
sed -i 's/ASFV_Heterocapsa_circularisquama_DNA_virus_01/sedis@ASFV_Heterocapsa_circularisquama_DNA_virus_01/' $1
sed -i 's/BACU_Adoxophyes_honmai_nucleopolyhedrovirus/BACU@_Adoxophyes_honmai_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Clanis_bilineata_nucleopolyhedrovirus/BACU@_Clanis_bilineata_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Helicoverpa_armigera_nucleopolyhedrovirus_G4/BACU@_Helicoverpa_armigera_nucleopolyhedrovirus_G4/' $1
sed -i 's/BACU_Mamestra_configurata_nucleopolyhedrovirus_B/BACU@_Mamestra_configurata_nucleopolyhedrovirus_B/' $1
sed -i 's/BACU_Spodoptera_exigua_multiple_nucleopolyhedrovirus/BACU@_Spodoptera_exigua_multiple_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Trichoplusia_ni_single_nucleopolyhedrovirus/BACU@_Trichoplusia_ni_single_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Lymantria_xylina_MNPV/BACU@_Lymantria_xylina_MNPV/' $1
sed -i 's/BACU_Ectropis_obliqua_nucleopolyhedrovirus/BACU@_Ectropis_obliqua_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Euproctis_pseudoconspersa_nucleopolyhedrovirus/BACU@_Euproctis_pseudoconspersa_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Orgyia_leucostigma_NPV/BACU@_Orgyia_leucostigma_NPV/' $1
sed -i 's/BACU_Leucania_separata_nucleopolyhedrovirus/BACU@_Leucania_separata_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Spodoptera_litura_nucleopolyhedrovirus/BACU@_Spodoptera_litura_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Bombyx_mandarina_nucleopolyhedrovirus/BACU@_Bombyx_mandarina_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Choristoneura_fumiferana_DEF_multiple_nucleopolyhedrovirus/BACU@_Choristoneura_fumiferana_DEF_multiple_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Agrotis_segetum_granulovirus/BACU@_Agrotis_segetum_granulovirus/' $1
sed -i 's/BACU_Choristoneura_occidentalis_granulovirus/BACU@_Choristoneura_occidentalis_granulovirus/' $1
sed -i 's/BACU_Pieris_rapae_granulovirus/BACU@_Pieris_rapae_granulovirus/' $1
sed -i 's/BACU_Phthorimaea_operculella_granulovirus/BACU@_Phthorimaea_operculella_granulovirus/' $1
sed -i 's/BACU_Cryptophlebia_leucotreta_granulovirus/BACU@_Cryptophlebia_leucotreta_granulovirus/' $1
sed -i 's/BACU_Spodoptera_litura_granulovirus/BACU@_Spodoptera_litura_granulovirus/' $1
sed -i 's/BACU_Xestia_c-nigrum_granulovirus/BACU@_Xestia_c-nigrum_granulovirus/' $1
sed -i 's/BACU_Plutella_xylostella_granulovirus/BACU@_Plutella_xylostella_granulovirus/' $1
sed -i 's/BACU_Neodiprion_lecontei_nucleopolyhedrovirus/BACU@_Neodiprion_lecontei_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Neodiprion_sertifer_nucleopolyhedrovirus/BACU@_Neodiprion_sertifer_nucleopolyhedrovirus/' $1
sed -i 's/BACU_Culex_nigripalpus_nucleopolyhedrovirus/BACU@_Culex_nigripalpus_nucleopolyhedrovirus/' $1
sed -i 's/HERP_Ostreid_herpesvirus_1/HERP@_Ostreid_herpesvirus_1/' $1
sed -i 's/NUDI_Oryctes_rhinoceros_nudivirus/NUDI@_Oryctes_rhinoceros_nudivirus/' $1
sed -i 's/NUDI_Heliothis_zea_nudivirus/NUDI@_Heliothis_zea_nudivirus/' $1
sed -i 's/ARCH_Crenarchaeota_Sulfolobus_solfataricus_2/ARCH@_Crenarchaeota_Sulfolobus_solfataricus_2/' $1
sed -i 's/HERP_Anguillid_herpesvirus_1/HERP@_Anguillid_herpesvirus_1/' $1
sed -i 's/HERP_Cyprinid_herpesvirus_3/HERP@_Cyprinid_herpesvirus_3/' $1
sed -i 's/HERP_Ictalurid_herpesvirus_1/HERP@_Ictalurid_herpesvirus_1/' $1
sed -i 's/HERP_Ranid_herpesvirus_1/HERP@_Ranid_herpesvirus_1/' $1
sed -i 's/HERP_Ranid_herpesvirus_2/HERP@_Ranid_herpesvirus_2/' $1
sed -i 's/NIMA_Shrimp_white_spot_syndrome_virus/NIMA@_Shrimp_white_spot_syndrome_virus/' $1
